# Generated by Django 3.2.5 on 2021-07-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('code', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('is_availibe', models.BooleanField(default=True)),
            ],
        ),
    ]
