# Generated by Django 3.2.5 on 2021-07-29 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['created', '-price']},
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
