# Generated by Django 3.2.5 on 2021-08-01 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='email',
        ),
    ]
