# Generated by Django 3.2.5 on 2021-07-13 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_update_product_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_availibe',
            new_name='is_availible',
        ),
    ]
