# Generated by Django 3.2.5 on 2021-09-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('eduction', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.ManyToManyField(to='products.Author'),
        ),
    ]
